export const SONGS = [
  { id:'love-story', title:'Love Story', album:'Fearless', year:2008, era:'Fearless', themes:['amor','esperanza','cuento'], moods:['romántica','optimista'] },
  { id:'you-belong-with-me', title:'You Belong With Me', album:'Fearless', year:2008, era:'Fearless', themes:['enamoramiento','no correspondido','amistad'], moods:['nostálgica','dulce'] },
  { id:'all-too-well', title:'All Too Well (10 Minute Version)', album:'Red', year:2021, era:'Red', themes:['recuerdo','corazón roto','duelo'], moods:['melancólica','catártica'] },
  { id:'we-are-never', title:'We Are Never Ever Getting Back Together', album:'Red', year:2012, era:'Red', themes:['ruptura','límite','empoderamiento'], moods:['enérgica','decidida'] },
  { id:'blank-space', title:'Blank Space', album:'1989', year:2014, era:'1989', themes:['sátira','autoimagen','fama'], moods:['irónica','pop'] },
  { id:'style', title:'Style', album:'1989', year:2014, era:'1989', themes:['atracción','cíclico','chispas'], moods:['cool','nocturna'] },
  { id:'out-of-the-woods', title:'Out of the Woods', album:'1989', year:2014, era:'1989', themes:['ansiedad','fragilidad','supervivencia'], moods:['intensa','cinemática'] },
  { id:'delicate', title:'Delicate', album:'Reputation', year:2017, era:'Reputation', themes:['nueva conexión','vulnerabilidad','fama'], moods:['íntima','suave'] },
  { id:'getaway-car', title:'Getaway Car', album:'Reputation', year:2017, era:'Reputation', themes:['escape','culpa','rebound'], moods:['cinética','dramática'] },
  { id:'lover', title:'Lover', album:'Lover', year:2019, era:'Lover', themes:['hogar','compromiso','ternura'], moods:['romántica','cálida'] },
  { id:'cruel-summer', title:'Cruel Summer', album:'Lover', year:2019, era:'Lover', themes:['pasión','secreto','verano'], moods:['eufórica','brillante'] },
  { id:'the-archer', title:'The Archer', album:'Lover', year:2019, era:'Lover', themes:['autoexploración','miedo','ansiedad'], moods:['etérea','vulnerable'] },
  { id:'cardigan', title:'cardigan', album:'folklore', year:2020, era:'folklore', themes:['nostalgia','primer amor','renacer'], moods:['envolvente','nostálgica'] },
  { id:'august', title:'august', album:'folklore', year:2020, era:'folklore', themes:['verano','anhelo','lo pudo ser'], moods:['aireada','melancólica'] },
  { id:'exile', title:'exile', album:'folklore', year:2020, era:'folklore', themes:['malentendidos','ruptura','perspectivas'], moods:['dolorosa','majestuosa'] },
  { id:'willow', title:'willow', album:'evermore', year:2020, era:'evermore', themes:['atracción','destino'], moods:['mística','suave'] },
  { id:'champagne-problems', title:'champagne problems', album:'evermore', year:2020, era:'evermore', themes:['propuesta fallida','salud mental','empatía'], moods:['triste','contemplativa'] },
  { id:'anti-hero', title:'Anti-Hero', album:'Midnights', year:2022, era:'Midnights', themes:['autocrítica','autoimagen','sombras'], moods:['confesional','pop'] },
  { id:'midnight-rain', title:'Midnight Rain', album:'Midnights', year:2022, era:'Midnights', themes:['elecciones','ambición','amor'], moods:['nocturna','reflexiva'] },
  { id:'fortnight', title:'Fortnight', album:'The Tortured Poets Department', year:2024, era:'The Tortured Poets Department', themes:['obsesión','memoria','repetición'], moods:['sombría','hipnótica'] },
]